### ISSUE TITLE
Remove all extra print statements

### ISSUE THREAD

**Issue by nimbusFarzaneh** [BCCDC-PHL/troika#7]
Remove extra print statements.

**Comment by dfornika** [comment]
I'd prefer to make as few changes to the codebase as possible. What's the rationale for removing all print statements?

**Comment by nimbusFarzaneh** [comment]
Because if we remove one, then we might as well remove all the other ones. Print statements, as you know, do not make any difference to the code, whatsoever. I am OK with leaving them in, but you wanted to remove them. So we might as well remove all of them.
